broadinstitute/gatk-protected

README.md, build.gradle
=> Adding documentation for building and running HDF5 on a Broad VM.

.travis.yml, src/main/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCounts.java, src/test/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCountsIntegrationTest.java
=> Output preTN files in the same format as TN files.

README.md
=> Issue 38 list r dependencies

README.md, src/main/java/org/broadinstitute/hellbender/tools/exome/PlotSegmentedCopyRatio.java
=> Moving from hg19 to b37

src/main/resources/org/broadinstitute/hellbender/utils/plotter/TangentResultsPlotting.R, src/test/java/org/broadinstitute/hellbender/tools/exome/PlotSegmentedCopyRatioIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/utils/plotting/PlotterTest.java
=> Issue 180 output qc files

build.gradle
this seems to fix the travis failures
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/hellbender-protected/186)
=> setting test jvm maximum memory

scripts/install_R_packages.R
Added a couple of missing parentheses.
=> Fixed minor typos in install_R_packages.R

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetCoverageUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetPadder.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/PadTargetsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/TargetPadderUnitTest.java
Fixed file extension that was causing test failure.
Updates to testing of the target padding.
Added documentation.
=> Added tool for padding targets in a way that will not generate overlap.

src/main/java/org/broadinstitute/hellbender/utils/hdf5/PoN.java, src/test/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCountsIntegrationTest.java
@kareembroad @vruano @achevali @LeeTL1220 This is what I was talking about yesterday.  It turns out that the entire beta hats code, aside from filtering out low-coverage targets, is a one-line matrix multiplication.
=> Simplify beta hats

src/main/java/org/broadinstitute/hellbender/utils/hmm/ForwardBackwardAlgorithm.java, src/main/java/org/broadinstitute/hellbender/utils/hmm/HiddenMarkovModel.java, src/main/java/org/broadinstitute/hellbender/utils/hmm/ViterbiAlgorithm.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/FlatRealTestHMModel.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/HMMUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/HeavyStateTestHMModel.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/TestHMModel.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/UninformativeTestHMModel.java
HMM api.
@davidbenjamin  please review.
=> Finite HMM api

docs/CNVs/CNVPoNFields.v5.0.md
Matlab script example is in another branch (PoN QC)
closes #120
=> Added docs

src/main/java/org/broadinstitute/hellbender/tools/exome/TargetCoverageUtils.java, src/main/java/org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCounts.java, src/test/java/org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCountsIntegrationTest.java
=> Issue 321 wgs pcov

src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java
=> Implemented some more checking of ACNV file outputs

src/main/java/org/broadinstitute/hellbender/tools/exome/FilterSamples.java, src/test/java/org/broadinstitute/hellbender/tools/exome/FilterSamplesIntegrationTest.java
=> Added sample filter tool.

src/main/java/org/broadinstitute/hellbender/tools/exome/FilterTargets.java, src/test/java/org/broadinstitute/hellbender/tools/exome/FilterTargetsIntegrationTest.java
=> Adds maximum target size filter to FilterTargets

src/main/java/org/broadinstitute/hellbender/tools/exome/SubtractCoverageComponents.java, src/test/java/org/broadinstitute/hellbender/tools/exome/SubtractCoverageComponentsIntegrationTest.java
=> Added numComponents argument to SubractCoverageComponents.  Closes #294.

src/main/java/org/broadinstitute/hellbender/utils/svd/OjAlgoAdapter.java, src/main/java/org/broadinstitute/hellbender/utils/svd/OjAlgoSingularValueDecomposer.java
I wrote an ojAlgo adapter class that could be useful to you.
Also modified OjAlgoSingularValueDecomposer to make use of that adapter.
I believe you also need a reverse-adapter. The SVD outputs 3 potentially large matrices. Each of those matrices are copied - twice.
=> OjAlgoAdapter

src/main/java/org/broadinstitute/hellbender/tools/exome/GetHetCoverage.java, src/main/java/org/broadinstitute/hellbender/tools/exome/HetPulldownCalculator.java, src/test/java/org/broadinstitute/hellbender/tools/exome/GetHetCoverageIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/HetPulldownCalculatorUnitTest.java
Also removed hetAlleleFraction parameter as it was a holdover from previous versions of HetPulldown where allelic skew was given as input.
=> Added base/mapping quality filters for HetPulldown

src/main/java/org/broadinstitute/hellbender/tools/exome/CombineReadCounts.java, src/test/java/org/broadinstitute/hellbender/tools/exome/CombineReadCountsIntegrationTest.java
@vruano do you have time to review this?
=> Closes #353 and rewrote tests to fail with the old code.

src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCNV.java, src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCount.java, src/main/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollection.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SNPSegmenter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SegmentMergeUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionModeller.java, src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/MinorAlleleFractionCache.java, src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCountUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollectionUnitTest.java
Also cleaned up AllelicCNV workflow class a bit.  Closes #332.
=> Added iterative MLE SNP segmentation with allelic bias and exposed some AllelicCNV arguments.

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/exome/Segment.java
`SimpleInterval.getSpanningInterval` moved to `IntervalUtils.getSpanningInterval`
=> updating gatk dependency to 4.alpha-122-ga4a6039-SNAPSHOT

src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateCoverageZScores.java, src/main/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollection.java, src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/CalculateCoverageZScoresIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollectionUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtilsTest.java
@vruano Could you review this?  It passes locally but Travis is taking forever.
=> Command line tool to convert read counts into target-specific Z scores

src/main/java/org/broadinstitute/hellbender/tools/exome/SubtractCoverageComponents.java
Approved by Sam once tests pass.
=> Fixing a stream-used-twice error

build.gradle
=> Increased VM heap size

src/main/java/org/broadinstitute/hellbender/tools/exome/CopyNumberTriStateSegmentCaller.java, src/main/java/org/broadinstitute/hellbender/tools/exome/DiscoverCopyNumberTriStateSegments.java, src/main/java/org/broadinstitute/hellbender/tools/exome/GenotypeCopyNumberTriStateSegments.java, src/main/java/org/broadinstitute/hellbender/utils/hmm/CopyNumberTriState.java, src/main/java/org/broadinstitute/hellbender/utils/param/ParamUtils.java, src/main/java/org/broadinstitute/hellbender/utils/tsv/TableReader.java, src/test/java/org/broadinstitute/hellbender/tools/exome/CopyNumberTriStateSegmentsCallerIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/DiscoverCopyNumberTriStateSegmentsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/GenotypeCopyNumberTriStateSegmentsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/utils/hmm/CopyNumberTriStateUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/tsv/TableReaderUnitTest.java
This new tool takes the segments discovered by the discovery tool and ask the question whether the same event is present in all the input samples.
The results ia a VCF quite similar to the one produced by XHMM.
Closes issue #147.
=> Adds a germline segment genotyper tool.

src/main/resources/org/broadinstitute/hellbender/utils/plotter/ACNVResultsPlotting.R, src/main/resources/org/broadinstitute/hellbender/utils/plotter/TangentResultsPlotting.R, src/test/java/org/broadinstitute/hellbender/utils/plotter/ACNVPlotterUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/plotter/CopyRatioSegmentedPlotterUnitTest.java
and quit with exit code recognizable by GATK.
=> Plotting R scripts check for missing input and output

src/main/java/org/broadinstitute/hellbender/cmdline/ExomeStandardArgumentDefinitions.java, src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCountCollection.java, src/main/java/org/broadinstitute/hellbender/tools/exome/HetPulldownCalculator.java, src/main/java/org/broadinstitute/hellbender/tools/exome/PlotACNVResults.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SampleCoverageStats.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SampleCoverageStatsReader.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SegmentUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetCoverageUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetTableReader.java, src/main/java/org/broadinstitute/hellbender/tools/exome/detectcoveragedropout/CoverageDropoutResult.java, src/main/java/org/broadinstitute/hellbender/utils/tsv/TableReader.java, src/main/java/org/broadinstitute/hellbender/utils/tsv/TableUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/ACNVModellerUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCountsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/PlotACNVResultsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/utils/plotter/ACNVPlotterUnitTest.java
Closes #411, closes #417, closes #434.
=> Minor fixes and refactoring.

src/main/java/org/broadinstitute/hellbender/tools/exome/ACNVCopyRatioModeller.java
=> Set segment-mean slice-sampling bounds.

.gitignore, build.gradle
adding a setupGatkLaunch task to gradle which extracts the gatk-launch script from the gatk dependency and places it in the root directory
updating gatk version
=> gradle extracts gatk-launch from the gatk jar

build.gradle
all the right properties from public were missing in protected. Also deflater binary was missing.
@droazen please have a look
=> add system properties and deflater to build

build.gradle
this is a stable non-snapshot release
=> updating gatk dependency to 4.alpha.1

build.gradle
add comment to clarify repo sections
copied verbatim from public
@lbergelson
=> Update build.gradle - add comment to clarify repo sections

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCounts.java, src/test/java/org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCountsIntegrationTest.java
Added more documentation for -L and making integration  test for basic check.
Closes #471
=> Expanded documentation and removing more contigs when requested.

src/test/resources/large/.gitattributes
this is necessary to make git-lfs work correctly
=> adding a .gitattributes file for git-lfs

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
protected part of https://github.com/broadinstitute/gatk/pull/1792
@droazen please review
=> HaplotypeCaller: don't bother spliting pileups by sample if there's just 1

scripts/wdl/README.md, scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/case_gatk_acnv_workflow_template.json
=> Issue 384 wdl

src/main/java/org/broadinstitute/hellbender/tools/exome/ACNVModeller.java, src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCNV.java, src/test/java/org/broadinstitute/hellbender/tools/exome/ACNVModellerUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java
Exposes more control over MCMC refitting performed during similar-segment merging, which can be useful for development.
Similar-segment merging is currently performed by traversing the genome and merging adjacent segments that have credible intervals that overlap in CR and MAF by a specified amount.  The credible intervals of a merged segment are updated in a heuristic manner.  After traversal, an MCMC fit is performed.  This procedure is repeated until convergence.
Because each MCMC fit is expensive, this yields longer runtimes for samples that are initially very segmented (e.g., LUAD).  For development purposes, it is nice to have more control over this runtime (beyond just limiting the number of iterations of merging allowed, which is already possible).  With the new argument …
=> Added option to disable or perform less MCMC refitting during similar-segment merging.

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMLikelihoodCalculationEngine.java
protected part of https://github.com/broadinstitute/gatk/pull/1822
reduces the amount of memory allocation by reusing the whole array and playing with indices rather than cutting slices of the array.
@lbergelson can you have a look?
=> less array allocation in PairHMMLikelihoodCalculationEngine

src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/TargetLikelihoodCalculator.java, src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/XHMMTargetLikelihoodCalculator.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CopyNumberTriStateSegmentRecordWriter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/hmm/CopyNumberTriStateHiddenMarkovModel.java, src/main/java/org/broadinstitute/hellbender/utils/hmm/CopyNumberTriState.java
@samuelklee can you review this?
=> Interface for coverage likelihoods.  Closes #533.

build.gradle
gatk public provides it so i removed it from here. 
fixes #540 
@lbergelson have a look
=> remove mllib from build script

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java
I reduced the amount of memory allocated in HaplotypeCaller by by reaching directly to bases and quals in ReferenceConfidenceModel
@lbergelson can you review?
=> less memory allocation in RCM by reaching directly to bases and quals

src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCNV.java, src/test/java/org/broadinstitute/hellbender/tools/exome/ACNVModellerUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java
Also some minor cleanup.
Closes #263.
=> Changed ACNV output filename tags so that alphabetical order corresponds to output order.

src/main/java/org/broadinstitute/hellbender/tools/exome/GetBayesianHetCoverage.java
=> Changed the default value for Het calling stringency from 5 to 30

scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/case_gatk_acnv_workflow_template.json
closes #519 @davidbenjamin Can you review this please?
=> Added plotting to the case sample workflow closes #519

scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/case_gatk_acnv_workflow_template.json
Closes issue #535 @davidbenjamin Could you please review this?
=> Added gc bias correction to case workflow closes #535

scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/case_gatk_acnv_workflow_template.json
Closes #604 , #528 , #520 @davidbenjamin Could you please review?
=> List input +SegmenterSplit step+segmenter params closes #604, #528 #520

build.gradle
=> update to using intel gkl - remove deflater

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMergerUnitTest.java
15% speedup to GenotypeGVCFs by reusing merger and calculators
@lbergelson can you review?
=> GenotypeGVCF speedup by reusing merger and calculators

scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/case_gatk_acnv_workflow_template.json, scripts/wdl/pon_gatk_workflow.wdl, scripts/wdl/pon_gatk_workflow_template.json, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ClusteringGenomicHMMSegmenter.java
closes #516 #523 @samuelklee Can you review this please?
=> Created PoN workflow, and added WGS option, closes #516 #523

scripts/wdl/README.md, scripts/wdl/case_gatk_acnv_workflow_template.json, scripts/wdl/pon_gatk_workflow_template.json
Made templates more like python templates.
Closes #603
=> Adding info and changes to cromwell json template.

src/main/java/org/broadinstitute/hellbender/tools/exome/acsconversion/ACSModeledSegmentUtils.java
=> Fixed inconsistent output of NaN values in ACNV -> ACS conversion.

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/LikelihoodEngineArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/MuTect2.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
Closes #668, closes #670, closes #675.  Various other code improvements.
@takutosato I did the same mini-integration test as before to sanity-check output. 
@kcibul keeping you in the loop.
=> Extract code shared between Mutect2 and HaplotypeCaller

scripts/docker/Dockerfile
=> Fixing minor issue in docker file where cache could be erroneous.

src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/CoverageModelUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/SexGenotypeDataCollection.java, src/main/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/TargetCoverageSexGenotypeCalculator.java, src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/CoverageModelUtilsUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/SexGenotypeDataCollectionUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/TargetCoverageSexGenotypeCalculatorUnitTest.java
See https://github.com/broadinstitute/gatk-protected/issues/715
=> Small updates to TargetCoverageSexGenotyper

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
To be shared between HaplotypeCaller and Mutect2.
=> Moved assembleReads() to the util class

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java, src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf, src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf, src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.vcf
Fix for https://github.com/broadinstitute/gatk/issues/2202.
=> Include sequence dictionary in HC/Mutect2 output.

src/main/java/org/broadinstitute/hellbender/tools/exome/pulldown/BayesianHetPulldownCalculator.java
... by filtering out non-ACTG bases when (1) walking the reference and (2) making a pileup.
=> Fixes an issue of GetBayesianHetCoverage with non- ACTG (e.g. N, X, etc) reference bases

src/main/java/org/broadinstitute/hellbender/tools/exome/AnnotateTargets.java, src/main/java/org/broadinstitute/hellbender/tools/exome/FilterSamples.java, src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionSamplers.java, src/main/java/org/broadinstitute/hellbender/tools/exome/copyratio/CopyRatioSamplers.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ClusteringGenomicHMM.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/SeqGraph.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/TestingReadThreadingGraph.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java, src/main/java/org/broadinstitute/hellbender/utils/SparkToggleCommandLineProgram.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/TestGraph.java
automatically generating @Override annotations where they were missing
This might prevent bugs if someone does a hamfisted refactoring.  I was doing it for htsjdk and gatk public so I figured I'd do it here too.
=> adding missing @Override

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/exome/alleliccount/AllelicCountWithPhasePosteriors.java, src/main/java/org/broadinstitute/hellbender/tools/exome/copyratio/CopyRatioSamplers.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/PosteriorProbabilitiesUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/eval/EvaluateCopyNumberTriStateCallsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/GenotypeCopyNumberTriStateSegmentsIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngineUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMLikelihoodCalculationEngineUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/PosteriorProbabilitiesUtilsUnitTest.java
=> Revved gatk public with ensuing refactoring in Mutect

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
=> Simplify Mutect2 read filtering

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
We need changes in the first two commits to run Mutect2.
=> Small changes to Mutect2

scripts/mutect2_wdl/mutect2-dream-eval-sge.json, scripts/mutect2_wdl/mutect2-dream-eval-sge.wdl, scripts/mutect2_wdl/mutect2-sge.json, scripts/mutect2_wdl/mutect2-sge.wdl, scripts/mutect2_wdl/sge.conf
`scripts/mutect2_wdl/mutect2-sge.wdl` takes the following parameters and runs GATK4 Mutect2 in SGE.
* gatk4 jar
* tumor bam (and its index, tumor sample name)
* normal bam (likewise)
* reference
* pon (optional)
* scatter count
`scripts/mutect2_wdl/mutect2-dream-eval-sge.wdl` takes a gatk4 jar and scatter count and runs the full dream evaluation.
An example input json for each case is also included.
=> General mutect2 wdl

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
=> Do not emit GVCF block definitions in the header

scripts/mutect2_wdl/mutect2.wdl, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
=> Artifact-in-normal filter AND two-pass M2 calling/filtering

src/main/java/org/broadinstitute/hellbender/tools/exome/ReadCountsReader.java
removing some duplicated code from ReadCountsReader constructors
removing an unused type parameter
=> removing duplicate code from ReadCountsReader

src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/AFCRHiddenState.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/AlleleFractionHiddenMarkovModel.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/AlleleFractionSegmenter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ClusteringGenomicHMM.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ClusteringGenomicHMMSegmenter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/CopyRatioHiddenMarkovModel.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/CopyRatioSegmenter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/JointAFCRHiddenMarkovModel.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/JointAFCRSegmenter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/JointSegmentationDatum.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformAlleleFractionSegmentation.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformCopyRatioSegmentation.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformJointSegmentation.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ScalarHMMSegmenter.java, src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/AlleleFractionHiddenMarkovModelUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/AlleleFractionSegmenterUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/CopyRatioSegmenterUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/JointAFCRSegmenterUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformCopyRatioSegmentationIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformJointSegmentationIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtilsTest.java
Passing locally but Travis is doing silly stuff.  Will assign @samuelklee to review once that's cleared up.
=> Infinite HMM joint segmentation

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
* use strand-agnostic allele fraction when we compute the strand-specific alt genotype likelihoods
* only sum over reads in one strand when we compute the strand-specific ref genotype likelihoods 
Strand-specific tumor lods look much more reasonable now
=> strand artifact annotation bug fix

scripts/wdl/case_gatk_acnv_workflow.wdl, scripts/wdl/pon_gatk_workflow.wdl
A quick bug fix. Addresses issue #893
=> Updated the filter name in the wdl script to the new naming convention

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java, src/test/resources/org/broadinstitute/hellbender/tools/mutect/createpon/sample1.vcf, src/test/resources/org/broadinstitute/hellbender/tools/mutect/createpon/sample2.vcf
@takutosato could you review this one, too? It's a brief one.
=> CLI to create somatic PoN

scripts/mutect2_wdl/mutect2.wdl, scripts/mutect2_wdl/mutect2_multi_sample.wdl, scripts/mutect2_wdl/mutect2_multi_sample_template.json, scripts/mutect2_wdl/mutect2_template.json, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/ClusteringGenomicHMM.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/ContaminationRecord.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/PileupSummary.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java, src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedVariantContextUtils.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContaminationIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummariesIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/PileupSummaryUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/GATKProtectedVariantContextUtilsUnitTest.java
Tool is tested on HCC1143 spike with 1%, 2%, 3%, 4%, and 5% NA12878.  Performance is great.  Also tested the WDL.
Note @takutosato @LeeTL1220 when you put the appropriate variants resource into the json for your own scripts, ask me for my ExAC common variants vcf.
=> Contamination tool

scripts/mutect2_wdl/unsupported/calculate_sensitivity.py, scripts/mutect2_wdl/unsupported/hapmap_sensitivity.json, scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl, src/main/java/org/broadinstitute/hellbender/engine/AbstractConcordanceWalker.java
Tested it and it works.  The Python script was adapted from broadinstitute/sock.
@takutosato can you review (not on your sick day, of course)?
=> crsp sensitivity wdl. Closes #878.

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
=> Update MuTect2 documentation about not computing obvious germline variants

scripts/mutect2_wdl/unsupported/mutect2_compare_tumors.wdl, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQuality.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBases.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPositionUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBasesUnitTest.java
* extracts parameters for some filters
* changes which annotations are turned in in M2 by default
* three new annotations  -- Arturo will experiment with these
=> Minor changes to Mutect filtering and annotation

scripts/mutect2_wdl/mutect2_multi_sample.wdl
In cromwell 25 we can now handle tumor-only multi-sample calling in a natural way.  I have tested this in tumor-only mode with call-caching (issue #896) and everything is fine.  @LeeTL1220 can you take a look?
=> Undo a cromwell workaround that is no longer necessary. Closes #896.

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
@LeeTL1220 Do you approve of starting at version 2.1?
=> Mutect version in vcf header. Closes #921.

scripts/mutect2_wdl/mutect2.wdl
@takutosato Harvesting some low-hanging fruit from our issues page.  I tested this.
=> Handles scatter_count == 1 in M2 WDL. Closes #908.

scripts/mutect2_wdl/mutect2-replicate-validation.wdl, scripts/mutect2_wdl/mutect2.wdl, scripts/mutect2_wdl/mutect2_multi_sample.wdl, scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl, scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl
@LeeTL1220 These changes let us run all the hapmap multiplexes and all the dream challenges from a single cromwell command.  They are tested and currently in use in my validations.
=> Use more sub-workflows in M2 WDL

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ClippedBases.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FragmentLength.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQuality.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PerAlleleAnnotation.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java, src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtils.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPositionUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
@LeeTL1220 This will put the new filters used in our most recent evaluations into master.
@takutosato I'm giving this to Lee because I'm about to assign the new somatic likelihoods PR to you for review, but it's worth acquainting yourself with the new filters we have.  
Note that some are not yet at all useful, but I'm anticipating that *maybe* they will be good covariates as part of an ML model.
=> Lots of new annotation and Mutect filters. Closes #964, #965.

build.gradle, src/test/java/org/broadinstitute/hellbender/tools/exome/conversion/allelicbalancecaller/AllelicSplitCallerUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/pon/coverage/pca/HDF5PCACoveragePoNCreationUtilsUnitTest.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/SharedVertexSequenceSplitterUnitTest.java, src/test/java/org/broadinstitute/hellbender/utils/hdf5/HDF5LibraryUnitTest.java
To match those used by GATK public.
=> Upgrade testNG and tests, add force resolution for some dependencies.

scripts/mutect2_wdl/mutect2.wdl
Should be the easiest pull request ever.
This just fixes a typo in the mutect2 wdl.
=> Fixes typo

scripts/mutect2_wdl/mutect2-replicate-validation.wdl, scripts/mutect2_wdl/mutect2.wdl, scripts/mutect2_wdl/mutect2_multi_sample.wdl, scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl, scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.wdl, scripts/mutect2_wdl/unsupported/mutect2_compare_tumors.wdl, scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl, src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervalsIntegrationTest.java
@LeeTL1220 Here you go.  The wdl changes are tested, with and without intervals specified.
=> New, simpler tool for splitting intervals and changes to M2 wdl.

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCounts.java, src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCountCollection.java, src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCountCollector.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CreateAllelicPanelOfNormals.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CreatePanelOfNormals.java, src/main/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCounts.java, src/main/java/org/broadinstitute/hellbender/tools/exome/SegmentUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/TargetTableReader.java, src/main/java/org/broadinstitute/hellbender/tools/exome/alleliccount/AllelicCountCollection.java, src/main/java/org/broadinstitute/hellbender/tools/exome/alleliccount/AllelicCountWithPhasePosteriorsCollection.java, src/main/java/org/broadinstitute/hellbender/tools/exome/conversion/acsconversion/ACSModeledSegmentUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/conversion/titanconversion/TitanFileConverter.java, src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java, src/main/java/org/broadinstitute/hellbender/tools/exome/plotting/PlotACNVResults.java, src/main/java/org/broadinstitute/hellbender/tools/exome/plotting/PlotSegmentedCopyRatio.java, src/main/java/org/broadinstitute/hellbender/tools/exome/samplenamefinder/SampleNameFinder.java, src/main/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/ContigGermlinePloidyAnnotationTableReader.java, src/main/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/TargetCoverageSexGenotyper.java, src/main/java/org/broadinstitute/hellbender/tools/pon/allelic/AllelicPanelOfNormals.java, src/main/java/org/broadinstitute/hellbender/tools/pon/allelic/AllelicPanelOfNormalsCreator.java, src/main/java/org/broadinstitute/hellbender/tools/pon/coverage/pca/HDF5PCACoveragePoNCreationUtils.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/MixingFraction.java, src/test/java/org/broadinstitute/hellbender/tools/pon/PoNTestUtils.java, src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf, src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf
-Updates to GenomicsDBImport (add --batchSize and --consolidate,
and provide a way to avoid downloading all headers up-front)
-Fix to RMSMappingQuality (don't blow up when 0 reads)
-Close threads properly in NIO code
-Allow HomRefBlock to handle GQs > 99 without blowing up.
=> Rev gatk public to 4.alpha.2-260-ge8d00ca-20170508.215840-1

scripts/mutect2_wdl/mutect2.wdl
Closes #918 and #1006.  @LeeTL1220 housekeeping using your proposed solution.
=> SplitIntervals now gives non-zero exit code if the gatk command fails

scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl, src/main/java/org/broadinstitute/hellbender/engine/AbstractConcordanceWalker.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/Concordance.java, src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceState.java, src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceIntegrationTest.java
@takutosato could you review this addition to the concordance tool?
=> Concordance emits an additional vcf of filtered true and false negatives

build.gradle, src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/germline/GermlineCNVCaller.java
updating to a new gatk public version
=> updating gatk to 4.alpha.2-271-gb05aee6-20170517.012235-1

build.gradle
This includes an important change to allele subsetting code that was causing differences with gatk3.
=> Update to 4.alpha.2-272-gf4d928f-20170517.201327-1

scripts/mutect2_wdl/mutect2.wdl, src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java, src/test/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBiasIntegrationTest.java, src/test/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtilsUnitTest.java
- Accidentally missed the same error occurring in other places.  Fixed here.
- Also, fixed WDL.
Closes #1043 
Closes #1044
=> Eliminated other erroneous ploidy errors.

src/main/java/org/broadinstitute/hellbender/tools/exome/CombineReadCounts.java
Add Documented Feature tag. A few minor wordings changed. Code untouched.
=> CNV CombineReadCounts: tag doc

src/main/java/org/broadinstitute/hellbender/tools/exome/AnnotateTargets.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CallSegments.java
Where can I find a list of the annotations that AnnotateTargets can call upon and their dependencies?
=> CNV AnnotateTargets: Shl doc annotate targets

src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCNV.java
Please let me know who to assign these doc changes to @LeeTL1220 @vdauwera.
This is the first of the gatk-protected doc changes I've made so the changes are prototypical. If you object to what I've decided to do, speak up soon before I make more doc changes @vdauwera @samuelklee. I've some forty tools to go.
In addition to adding the doc tag, I went ahead and added in the WDL commands as example commands. For this tool, there were two example commands, one for WGS and another for other data types, e.g. WES. Because I use the WDL commands _as is_, I also added in a codeblock section to show the variable types (Int, File etc). This _as is_ format I think is understandable by folks who will not use WDLs, quick for me to incorporate and also enables folks who want to WDL'ize the commands, …
=> CNV AllelicCNV: Shl doc alleliccnv

src/main/java/org/broadinstitute/hellbender/tools/exome/PerformSegmentation.java
- Is the R and R component requirement still the case?
- Does the script at https://github.com/broadinstitute/gatk-protected/blob/master/scripts/install_R_packages.R
still apply?
---
--log2Input WES/WGS=true default=false
--undoSD default=3 WES=2 WGS=3
=> CNV PerformSegmentation: tag doc, note R requirement and give example commands

LICENSE.txt, README.md
Open soooooource all the things
=> Update license and readme

src/main/java/org/broadinstitute/hellbender/tools/exome/convertbed/ConvertBedToTargetFile.java
Should pin down exactly which of the Picard/GATK formats this 4-column output corresponds to:
```
*         contig  start   stop    name
*         chr1    11869   12227
*         chr1    12613   12721
```
=> CNV ConvertBedToTargetFile: tag doc, give example command and pad intro

src/main/java/org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCounts.java
- Who is the author of SparkGenomeReadCounts?
- Doesn't this tool need at least contig intervals, e.g. passed in via -L, to parallelize over Spark workers? 
- I will use the following opening, is it ok?
```
/**
* Calculates read coverage on whole genome sequencing (WGS) alignments using Spark.
```
=> CNV SparkGenomeReadCounts tag doc; example WGS command

scripts/mutect2_wdl/mutect2-replicate-validation.wdl, scripts/mutect2_wdl/mutect2.wdl, scripts/mutect2_wdl/mutect2_multi_sample.wdl, scripts/mutect2_wdl/unsupported/calculate_sensitivity.py, scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl, scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.json, scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.wdl, scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl
@takutosato can you review this?
=> Polishing M2 wdls

src/main/java/org/broadinstitute/hellbender/tools/exome/CreatePanelOfNormals.java
Questions ~~yet to be~~ answered:
4. For CreatePanelOfNormals is the spark option now working? I see in the WDL we do not use the --disableSpark option.
5. How can I explain the target_weights.txt file?
=> CNV CreatePanelOfNormals: tag doc, add example command

src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformAlleleFractionSegmentation.java
- No example command since there is no WDL for me to reference. FYI @LeeTL1220 @achevali.
- tag doc and mention that the tumorHets file is from GetHetCoverage.
=> CNV performallelefractionsegmentation: tag doc

src/main/java/org/broadinstitute/hellbender/tools/exome/eval/ConvertGSVariantsToSegments.java
Just incorporated what I learned, despite also learning this will be an internal tool.
Please let me know the information is correct @vruano. Thank you.
=> CNV ConvertGSVariantsToSegments: tag doc, give example command and example output

src/main/java/org/broadinstitute/hellbender/tools/exome/eval/EvaluateCopyNumberTriStateCalls.java, src/main/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentCaller.java, src/main/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentGenotyper.java
Tagged:
- EvaluateCopyNumberTriStateCalls
- XHMMSegmentCaller
- XHMMSegmentGenotyper
And tweaked command given in EvaluateCopyNumberTriStateCalls
=> CNV 3 tools: tag docs; label internal in one-line summary

src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformCopyRatioSegmentation.java
- experimental tool, so no example command
=> CNV PerformCopyRatioSegmentation: tag doc

src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCounts.java, src/main/java/org/broadinstitute/hellbender/tools/exome/CreateAllelicPanelOfNormals.java
- CollectAllelicCounts: tag doc, add example command, add example interval list and add example results
- CreateAllelicPanelOfNormals: add experimental tag. No command given experimental.
=> CNV CollectAllelicCounts and CreateAllelicPanelOfNormals

src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformCopyRatioSegmentation.java, src/main/java/org/broadinstitute/hellbender/tools/exome/segmentation/PerformJointSegmentation.java
- Experimental tools without WDL so again, no example command.
PerformCopyRatioSegmentation and PerformJointSegmentation: Label experimental and add description to top of doc section
=> CNV PerformJointSegmentation: tag doc

src/main/java/org/broadinstitute/hellbender/tools/exome/sexgenotyper/TargetCoverageSexGenotyper.java
Much smoothing to be desired but this is what it is right now.
=> CNV TargetCoverageSexGenotyper: tag doc, give example command and add notes from MB's email
