.travis.yml
README.md

Note the branch name is a misnomer, I ended up just adding a "force-yes" flag.  Not quite sure why some of the R packages aren't being authenticated properly, but the build succeeds now.

Changing apt-key command and fixing Travis badge.

---

.travis.yml

adding a 1gb limit to the gradle jvm to try and stop the intermittent out of memory errors
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/hellbender-protected/192)

adding gradle jvm memory limit

---

README.md

Looks like the repo wasn't activated on coveralls after the name change, should be fixed now.

Updated coveralls badge.

---

src/main/java/org/broadinstitute/hellbender/tools/exome/PerformSegmentation.java
src/main/java/org/broadinstitute/hellbender/utils/segmenter/RCBSSegmenter.java
src/main/resources/org/broadinstitute/hellbender/utils/segmenter/CBS.R
src/test/java/org/broadinstitute/hellbender/tools/exome/PerformSegmentationIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/segmenter/SegmenterUnitTest.java

Closes #325 
Exposes most of the remaining parameters.
Testing only checks that values in the output actually change.  Exact changes would be very onerous to test.  ``trim`` could not be tested this way.  However, output of the R script indicated that alternate values of ``trim`` were being passed in.

Exposed a lot more CBS parameters for PerformSegmentation CLI.

---

src/main/java/org/broadinstitute/hellbender/tools/exome/AllelicCNV.java
src/main/java/org/broadinstitute/hellbender/tools/exome/SegmentMergeUtils.java
src/main/java/org/broadinstitute/hellbender/tools/exome/allelefraction/AlleleFractionModeller.java
src/test/java/org/broadinstitute/hellbender/tools/exome/PlotSegmentedCopyRatioIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/exome/SegmentMergeUtilsUnitTest.java

By default.  Also added flag to allow use of all CR segments and changed some default parameter values to those used in evaluation.  Closes #331, closes #333.

Changed ACNV segment union to only use CR segments not called neutral.

---

src/main/java/org/broadinstitute/hellbender/tools/exome/AnnotateTargets.java
src/main/java/org/broadinstitute/hellbender/tools/exome/GetHetCoverage.java
src/main/java/org/broadinstitute/hellbender/tools/exome/PoNIssueDetector.java
src/main/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollection.java
src/main/java/org/broadinstitute/hellbender/tools/exome/TargetTableAnnotationManager.java
src/test/java/org/broadinstitute/hellbender/tools/exome/AllelicCNVIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/exome/CalculateCoverageZScoresIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/exome/GetHetCoverageIntegrationTest.java

To be used for allelic-PoN exploratory work where the tumor pulldown is not needed.

Added normal-only mode to GetHetCoverage.

---

build.gradle

I messed up the shadow and spark jars with my previous commit.  I thought the settings on the jar task would propogate to the shadow tasks, but it turns out they didn't.  I'd checked to make sure that they still had a manifest, but it turned out they had an empty manifest.
This fixes it.

fix the incomplete manifest in sparkJar and shadowJar

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java

The HaplotypeBamWriter was being created in the wrong place,
causing the bam produced by -bamout to be truncated.
Fixed this and added an integration test for the -bamout
argument.
Resolves #465

Fix -bamout HaplotypeCaller argument

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/RefVsAnyResult.java

The String was built regardless of whether the test fails or succeeds which was wasteful. Shows up on HC profile.
@lbergelson, ok?

eliminate eager string construction in assertion. Takes 3% of runtime of HC

---

src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtils.java
src/main/java/org/broadinstitute/hellbender/utils/hmm/HiddenMarkovModel.java
src/test/java/org/broadinstitute/hellbender/tools/exome/CopyNumberTriStateSegmentsCallerIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtilsTest.java
src/test/java/org/broadinstitute/hellbender/utils/hmm/HMMUnitTest.java

This is going to make writing tests for the germline (and possibly later somatic) segmentation easier.  As an example, this PR already uses the new method to simplify a lot of code in the germline integration tests.
@samuelklee would you mind taking a look at this?

Added a method for HMMs to generate a random hidden sequence. Closes #456.

---

README.md
src/main/java/org/broadinstitute/hellbender/tools/exome/TargetPadder.java
src/main/java/org/broadinstitute/hellbender/utils/hdf5/HDF5File.java
src/main/java/org/broadinstitute/hellbender/utils/hdf5/HDF5PoN.java
src/main/java/org/broadinstitute/hellbender/utils/hdf5/HDF5PoNCreator.java
src/test/java/org/broadinstitute/hellbender/utils/hdf5/HDF5LibraryUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/hdf5/HDF5PoNCreatorUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/hdf5/PoNTestUtils.java

This was necessary for WGS PoNs.  Even really small PoNs were taking days to finish writing to disk.  The solution was to transpose some of the fields to minimize the number of rows.  The HDF5PoN class has been altered to make the transposing encapsulated away from callers.
Other notes:
- Added hook to create a PoN from a ReadCountCollection, which is much more flexible than insisting on an input file.
- Added flush to the closing of a PoN.  This probably does not do much.
- Minor doc changes.
- More logging during PoN creation.  Makes it look like it is making progress...
Closes #494 
Closes #493 
Removing possibly extraneous instantiation of RamPoN in hopes of saving some RAM during PoN creation
Updated docs.
Updated docs with minor comment.
Updated docs with minor comment.
Updated to …

Speeding up the writing to disk of a PoN 

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/BaseGraph.java
src/main/java/org/broadinstitute/hellbender/utils/svd/SparkSingularValueDecomposer.java
src/test/java/org/broadinstitute/hellbender/tools/exome/SampleCoverageStatsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/Civar.java
src/test/java/org/broadinstitute/hellbender/utils/codecs/LineIteratorReaderUnitTest.java

squid:UselessParenthesesCheck - “ Useless parentheses around expressions should be removed to prevent any misunderstanding ”. 
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck

Useless parentheses around expressions should be removed

---

src/main/java/org/broadinstitute/hellbender/tools/exome/PoNIssueDetector.java
src/main/java/org/broadinstitute/hellbender/tools/exome/SNPSegmenter.java
src/main/java/org/broadinstitute/hellbender/tools/exome/acsconversion/ACSModeledSegmentUtils.java
src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedMathUtils.java
src/main/java/org/broadinstitute/hellbender/utils/mcmc/PosteriorSummaryUtils.java
src/main/java/org/broadinstitute/hellbender/utils/spark/SparkConverter.java
src/main/java/org/broadinstitute/hellbender/utils/svd/ApacheSingularValueDecomposer.java
src/main/java/org/broadinstitute/hellbender/utils/svd/OjAlgoSingularValueDecomposer.java
src/main/java/org/broadinstitute/hellbender/utils/svd/SparkSingularValueDecomposer.java
src/test/java/org/broadinstitute/hellbender/utils/svd/SVDTestUtils.java

squid:S1118 - “Utility classes should not have public constructors ”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1118

Utility classes should not have public constructors

---

src/main/java/org/broadinstitute/hellbender/utils/tsv/TableUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/Civar.java

squid:S2131 - “Primitives should not be boxed just for "String" conversion”. 
https://dev.eclipse.org/sonar/rules/show/squid:S2131

Primitives should not be boxed just for "String" conversion

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyRegionTestDataSet.java

squid:S2130 - “ Parsing should be used to convert "Strings" to primitives”. 
https://dev.eclipse.org/sonar/rules/show/squid:S2130

Parsing should be used to convert "Strings" to primitives

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyRegionTestDataSet.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/Civar.java

squid:S1149 - “Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used ”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1149

Synchronized classes Vector, Hashtable, Stack and StringBuffer shouldnot be used

---

build.gradle

add mavenLocal to gradle to simplify 2-repo development.
with this change i just need to add 1 line when changing the snapshot build of gatk
I put local before central because it seems to me that local copies should override global ones. conflicts should be very rare
@lbergelson wdyt?

add mavenLocal to gradle

---

.gitignore
scripts/docker/Dockerfile
scripts/docker/README.md
src/main/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCounts.java

Closes #386 
Closes #501 
**Please note that this pull request assumes that the next release will be alpha-1.3 for the docker image.  It was tested on alpha-1.2**
Also, added warning if the pon version does not match the latest version in NormalizeReadCounts.
Adding warning if the PoN is not the current version in NormalizeSomaicReadCounts.
Setting to be the next version number of gatk-protected.
Adding plotting error dump to gitignore

Pegging docker to alpha1.3

---

src/main/java/org/broadinstitute/hellbender/tools/exome/BayesianHetPulldownCalculator.java

Closes #561 
Very simple change.  After running on WGS samples , speed did not seem to improve much.  Leaving in the change, since, according to the javadoc, the index should not hurt performance.

Enabling the index.

---

.gitignore
README.md
scripts/docker/Dockerfile
scripts/docker/README.md
scripts/docker/build_docker.sh
scripts/install_git_lfs.sh

Closes #575 
Closes #590 
Build a docker image based on a github tag in the github gatk-protected repo (``build_docker.sh``).
- Supports automated pushing to ``https://hub.docker.com/r/broadinstitute/gatk-protected/``
- Insists on unit testing on the docker image before pushing
- Supports git hashes and pushing those to dockerhub
- Disallows git hashes posted as ``latest`` tag in dockerhub
- Can build images without pushing to docker hub
- Building an image takes a long time (over one hour)
- Requires sudo to run and checks
- Basic use cases documented in README
- Running of unit tests is *not* part of the ``docker build ...  ``
- Will automatically remove the docker container after unit tests complete, by default.  This can be disabled for debugging of failed unit tests.

Automated docker build with unit tests and automated pushing.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMLikelihoodCalculationEngine.java

@akiezun or @eitanbanks 
For some sources of data, the base qualities after recalibration are quite low.  While the data is not ideal, I do still want to include base qualities below Q18 and so I added this option.  I am not sure about how to test this repo, as I ran `./gradlew test` and got many tests that failed that were unrelated to this change, so perhaps you can test this PR and let me know how you did it?

Expose the PairHMM Base Quality Score Threshold in HaplotypeCaller.

---

build.gradle

This fixes it for me in my docker image.  @LeeTL1220 Could you test this.  Don't merge this yet, I'd like to wait until we merge https://github.com/broadinstitute/hdf5-java-bindings/pull/6 and have a non-snapshot version.

fix hdf5 test failures

---

scripts/acnv_cromwell_tests/case_gatk_acnv_workflow_exome.json
scripts/acnv_cromwell_tests/case_gatk_acnv_workflow_wgs.json
scripts/acnv_cromwell_tests/pon_gatk_workflow_exome.json
scripts/acnv_cromwell_tests/pon_gatk_workflow_wgs.json
scripts/acnv_cromwell_tests/run_acnv_pipelines.sh
scripts/wdl/README.md
scripts/wdl/case_gatk_acnv_workflow.wdl
scripts/wdl/case_gatk_acnv_workflow_template.json
scripts/wdl/pon_gatk_workflow.wdl
scripts/wdl/pon_gatk_workflow_template.json

Closes #680 
Travis.yml wasn't properly evaluating the tests of the acnv workflows, as it did not fail if one of the workflows fails. 
Also I disabled QC for Travis tests since the CreatePanelOfNormals threw out all samples on the test data.

Fixed travis evaluation of the acnv workflow

---

build.gradle

This brings in the ploidy bug fix for the HaplotypeCaller

Rev gatk-public dependency to 4.alpha.2-63-g13f88ae-20161016.062553-1

---

build.gradle

This version includes the fix for the QSS VCF header bug

rev gatk-public dependency to 4.alpha.2-67-gce8ce3a-20161024.213859-1

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/PerAlleleCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

* Closes issues #733, #735, and #807.
* Gets rid of a lot of arbitrary filters that have probably become obsolete
* moves filtering into a second pass
* deals with a lot of little TODOs
* emits all somatic alleles
* annotates the output vcf more than before

Refactoring to prepare Mutect2 for model improvements

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java

@takutosato This PR just moves methods around a bit.  It fixes the aesthetically offensive inheritance of `SomaticGenotypingEngine` from `HaplotypeCallerGenotypingEngine`.

Extract common parent for M2 and HC GenotypingEngines.  Fixes #811.

---

build.gradle

We really shouldn't have a compile dependency on tools.jar; doing so propagates it through the uber.jar. Building and testing seem to pass without it. If there is another gradle target (or some runtime code) that requires it, we can try to address that. Otherwise the dependency should be removed.

Remove tools.jar dependency.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CountFalsePositives.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CountFalsePositivesTest.java

@davidbenjamin I wrote a simple tool for mutect2 NA12878 validation. It takes a list of vcfs, counts the number of SNP and INDEL variants (i.e. PASS variants) in each file, and prints the counts in a tsv format. Please take a look!

New tool that counts false positives in a vcf to be used for mutect2 NA12878 normal-normal validation

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java

@takuto this addresses an issue in gatk-public, making the format more standard and eliminating several annoying lines of code.

Handle samples better in Mutect header

---

scripts/mutect2_wdl/mutect2.wdl

@davidbenjamin This change adds runtime clauses to `mutect2.wdl`. Now this single wdl can run in the cloud and on SGE. Users must supply the runtime parameters (e.g. `$__docker__`) themselves. I have a script that populates those parameters for broad internal uses; this script will live in the palantir repo under `Analysis/mutect2-evaluation`. Cromwell ignores runtime clauses when irrelevant (e.g. when we submit the jobs to SGE).
I also modified the code surrounding `glob` so it works on cromwell v24; in v24 and later, cromwell `glob` looks for files in the current working directory only.

add runtime clauses and fix glob

---

README.md
build.gradle

-Add a new "gradle localJar" target that just runs shadowJar
-The localJar/shadowJar name now ends in a "local.jar" suffix, to
better distinguish it from the spark jar. This is consistent with
gatk public, and (critically) with the names that the gatk-launch
script now expects. This fixes a failure in gatk-launch.
-Kept "gradle shadowJar" around for backwards compatibility, but removed
mention from README
-Include the word "package" in the name for jars that contain all dependencies
(again, for consistency with gatk public)
-Updated the README with basic information on building and running
GATK4 copied from the public README, with links back to the public
README for further details.
Resolves #873

Add "gradle localJar" as replacement for "gradle shadowJar", and adjust jar naming to be consistent with public

---

scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.wdl

I checked, and empty intervals in the input are *not* a problem.

removed redundant task in hapmap wdl. Closes #917

---

src/main/java/org/broadinstitute/hellbender/engine/AbstractConcordanceWalker.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

At least on our DREAM challenge integration tests, it turns out that `isActive()` in `Mutect2Engine` was: 1) too permissive of sites including, *some with zero evidence of variation whatsoever*; 2) prone to throwing away good variants; 3) sufficiently complex that the act of determining activity itself, as opposed to the consequence of genotyping too many inactive sites, took a significant amount of time.
This simplification improved sensitivity on DREAM 3 and DREAM 4by a bit while running about three times as fast.  Based on these results, as well as manual review in IGV of several hundred sites, I feel pretty confident in this change.  I am currently running the CRSP sensitivity validation with the old code, so we will have a point of reference.

Simplified M2 isActive, increasing speed and sensitivity. Closes #801.

---

build.gradle

This includes a fix to gatk-launch

Rev GATK public dependency to 4.alpha.2-188-g7332d10-20170321.172613-1

---

README.md

Github changed how it's markdown parser handles headers.  It used to accept `#SomeHeader` but now requires a space, i.e. `# SomeHeader`.
Updating to the readme to match the new markdown syntax.

fixing headers in README

---

src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java
src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java
src/test/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBiasIntegrationTest.java

Closes #939 
This simply adds the orientation bias filter results to the FILTER field if any genotype has it.
As requested by Chip from CGA.

Added orientation bias filter results to the FILTER field.

---

build.gradle

This moves us to a snapshot of gatk-public that takes the version gatk-protected
currently depends on (4.alpha.2-188-g7332d10) and applies JUST @davidbenjamin 's fix
to the TandemRepeat annotation to it.
This is necessary to unblock @davidbenjamin 's work, because the HaplotypeCaller
tests are failing if we update protected to the latest public HEAD, and although we've
fixed some of the issues there are still some unexplained failures in the concordance tests.

Move to a snapshot of gatk-public based on 4.alpha.2-188-g7332d10 with TandemRepeat fix applied

---

build.gradle
src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java

* Includes a fix to GenotypingEngine in public necessary to get the
HaplotypeCaller tests passing with the latest gatk-public
* Updated HaplotypeCallerIntegrationTest to use "-stand_call_conf 30.0"
for now, so that we don't have to deal with the migration to a default
stand_call_conf of 10.0 just yet.

Rev GATK dependency to 4.alpha.2-214-g09b380e-20170405.195304-1

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java

@takutosato You saw the improvement in sensitivity on DREAM.  HapMap showed the same.  Normal-normal false positives were about the same.  Most of the changes are straightforward.  The stuff about `perSampledFilteredReadList` is that we used to keep track of filtered reads in order to annotate based on those.  1) I don't think that makes much sense.  2) We can't do that any longer because those reads are filtered before `Mutect2Engine` see them.
@LeeTL1220 You might be interested in knowing that this improved sensitivity in all the DREAM challenges by about 3%.
@droazen @yfarjoun @ldgauthier HaplotypeCaller has the same comment as Mutect asking whether this change is worthwhile.  Might be worth investigating making the change there, too.

Filter reads before assembly in Mutect. Closes #723.

---

build.gradle

This snapshot includes a change to make it easier to use GenotypeGVCFs
with GenomicsDB input: JSON files no longer need to be explicitly
provided on the command line.

Rev gatk-public to 4.alpha.2-234-gc3a44c9-20170427.144324-1

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMergerUnitTest.java

fixing a site in ReferenceConfidenceVariantContextMerger where a String
was expected but an Integer was being provided in some circumstances
GenomicsDB creates variants with MIN_DP as an integer instead of a String which was causing a ClassCastException
should fix #1014, but I don't have access yet to the files that produced the error so I can't check

fixing ClassCastException  when running GenotypeGVCFs against GenomicsDB

---

build.gradle

This brings in a bug fix to the FS annotation to make it match R,
as well as some GenomicsDB-related test utilities.

Rev gatk-public dependency to 4.alpha.2-236-g1dde31b-20170427.202410-1

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java

it previously didn't honor the engine arguments for creating index files but it does now
fixes broadinstitute/gatk#2635

making GenotypeGVCFs write index files

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCounts.java
src/main/java/org/broadinstitute/hellbender/tools/exome/CreateAllelicPanelOfNormals.java
src/main/java/org/broadinstitute/hellbender/tools/exome/GetBayesianHetCoverage.java
src/main/java/org/broadinstitute/hellbender/tools/exome/GetHetCoverage.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/common.html
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html

Until we resolve how we're going to integrate gatk-protected doc with gatk-public, the comms team needs a way to generate/review doc for protected tools. This PR adds the same docgen process we use for public, with the exception that you also need to have a GATK clone to run it, since javadoc from any dependent engine classes needs to be available.
I also tagged a handful of tools with @DocumentedFeatureObject so I could test the process manually.

Add ability to generate tool documentation.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java

@takutosato This change will emit and then filter variants with low but not too low tumor lods.  This will be useful for analyzing false negatives and making ROC curves.

separate emitting from filtering based on tumor lod

---

src/main/java/org/broadinstitute/hellbender/tools/exome/CallSegments.java

For CallSegments, the --legacy parameter needs clarification.
- Is python ReCapSeg the main legacy data? 
- Can folks use non-python ReCapSeg? Other data? 
- Why is there a "NOTE" that the output is in the tool's format? Is there reason to expect a different format? I'd like to omit this note. Is that okay?
```
--legacy,-LEG:Boolean         (Advanced) Assume that the input seg file is using the legacy format (e.g. generated by
python ReCapSeg).  NOTE:  The output will be in the format used by this program -- i.e. no
preservation of legacy field names, etc.  Default value: false. Possible values: {true,
false} 
```

CNV CallSegments: tag doc and give example command

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java

Somehow during refactoring, the line in the HaplotypeCaller that checks
whether an event starts in the current shard got changed to instead check
that the event is completely contained in the current shard. This means that
events spanning shard boundaries would be dropped completely.

Fix regression in HaplotypeCaller with shard boundary check

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java

outputing a more specific exception in GenotypeGVCFs
fixing testIntervalsAndOnlyOutputCallsStartingInIntervalsAreMutuallyRequired which was not really testing the appropriate condition

fix test in GenotypeGVCFsIntegrationTest

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java

Previously the tool was outputting calls that were completely contained within
the current shard.
Resolves #1081

Mutect2: only output calls that *start* in the current shard

---

src/main/java/org/broadinstitute/hellbender/tools/exome/ConvertACNVResults.java

ConvertACNVResults original summary blurb:
```
Convert files into TITAN and Broad CGA Allelic CapSeg (ACS) formats.  This tool uses spark, though running locally is fine.
As part of this process, this tool generates calls whether a particular segment is balanced (MAF=0.5)
IMPORTANT:  The additional CNLoH calls from this tool should be treated with a lot of skepticism.  Preliminary results indicated very poor performance.
```
- Eventually we will need a description and example of the TITAN format.
- Eventually we will need a description and example of Broad CGA Allelic CapSeg (ACS) format.
- "This tool uses spark, though running locally is fine." Is using Spark the default? What parameters are involved to use or not use Spark (e.g. --sparkMaster)? Can I instead say "To enable Spark, use …

CNV ConvertACNVResults: tag doc, give example command, question summary

---

src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java

What exactly does the tool do to "behaves intelligently when padding consecutive targets naively would yield overlapping targets"? I think it's important to mention how the tool resolves overlaps in padding.

CNV PadTargets: tag doc and give example command

---

build.gradle

This works around an issue where the docgen field search code tries to reflect on inaccessible JVM classes such as Throwable, and allows the docgen process to be run locally. This change affects dogcen only.

Change docgen field search order.

---

src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java

Example command is only for WES data. For WGS, I point users to SparkGenomeReadCounts.
- I nudge users to use PadTargets to pad their targets and tell them the target intervals do not overlap. I also state NOT to use BED format and point them to ConvertBedToTargetFile.
- I leave in the optional reference to safeguard newbie users. I do state that 
```
The reference is optional if --disableSequenceDictionaryValidation is set to true.
```
- description for targets param changed to specify 1-based indexing. 
- Default params changed for:
--groupBy SAMPLE 
--transform PCOV 
--targetInformationColumns FULL

CNV CalculateTargetCoverage: tag doc; example WES command; change defaults

---

src/main/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCounts.java

6. For NormalizeSomaticReadCounts, in the WDL I see two additional optional output files that I've not seen before--the Fnt and betaHats:
```
*   --input coverage.tsv \
*   --panelOfNormals cnv_panel_of_normals.pon \
*   --tangentNormalized ${entity_id}.tn.tsv \
*   --factorNormalizedOutput ${entity_id}.fnt.tsv \
*   --preTangentNormalized ${entity_id}.preTN.tsv \
*   --betaHatsOutput ${entity_id}.betaHats.tsv
```
Do we now recommend these be output as well? Or shall I stick to the Vancouver demo's simplified command with just PTN and TN?
7. For NormalizeSomaticReadCounts, in contrast to the WDL, I've removed the --targets option. If I recall, this is no longer necessary because it was already applied upstream in the workflow. Is this okay?
8. For NormalizeSomaticReadCounts, there is a …

CNV NormalizeSomaticReadCounts: tag doc and provide example command

---

src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/germline/GermlineCNVCaller.java

- For @vdauwera:
GermlineCNVCaller's doc-- some of the parameters are described up top and should be moved to the actual parameter's section. I didn't do this because the descriptions up top link to e.g. {@link ReadCountCollectionUtils}, which when put into quotes, I'm not sure how they will appear, given we cannot yet generate the docs via autodoc (getting fixed currently).
It would be great when we will finally be able to generate the docs so I can understand how the formatting appears.
- @cmnbroad clarifies that we will indeed have a tag for experimental tools so I will not add this in the tool doc text itself and will wait to add this tag, which this tool needs.
Now lives at  #`/humgen/gsa-scr1/pub/bundle/beta/GermlineCNVCaller`:
Many thanks to MB for having these on hand.

CNV GermlineCNVCaller: tag doc, give two example commands, point to results folders

---

src/main/java/org/broadinstitute/hellbender/tools/exome/plotting/PlotSegmentedCopyRatio.java

For PlotSegmentedCopyRatio, what are the "CONTIG_DELIMITER"s? The --sequenceDictionaryFile parameter mentions that contig names should not have these but doesn't define what these are:
```
--sequenceDictionaryFile,-SD:File
File containing the reference sequence dictionary (used to determine relative contig
lengths). Contigs will be plotted in the order given. Contig names should not include
"CONTIG_DELIMITER".Data on contigs not in the dictionary will not be plotted and warning
will be thrown.  Required. 
```

CNV PlotSegmentedCopyRatio: tag doc, add example command, clarify -SD parameter

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithBamDepth.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithExpectedAlleleFraction.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/CalculateMixingFractions.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/RemoveNearbyIndels.java

Tagged and labeled 'internal' the following four tools:
- AnnotateVcfWithBamDepth
- AnnotateVcfWithExpectedAlleleFraction
- CalculateMixingFractions
- RemoveNearbyIndels
Other than some formatting changes, did not change other content.

Other tools: tag docs, label internal, add minimal formatting

---

src/main/java/org/broadinstitute/hellbender/tools/exome/AnnotateTargets.java
src/main/java/org/broadinstitute/hellbender/tools/exome/eval/ConvertGSVariantsToSegments.java
src/main/java/org/broadinstitute/hellbender/tools/exome/gcbias/CorrectGCBias.java

- Besides the usual doc changes, updated the following:
```
oneLineSummary = "Correct for per-sample GC bias effects",
summary = "Correct coverage in read counts by estimating per-sample bias as a function of target GC " +
"content and dividing input coverage by these derived bias curves.",
```
to refer to _per-target_ instead of per-sample.
- In addition, updated the output name of `AnnotateTargets.java` to match the input of CorrectGCBias: targets.annotated.tsv

CNV CorrectGCBias: Shl doc correct gc bias
